import Matter, { type Body as MatterBody, type Engine as MatterEngine } from "matter-js";

const { Bodies, Body, Composite, Engine, Events, Vertices } = Matter;

const giantPandaTierIndex = 9;
const maximumRegularTierIndex = 12;
const matterBaseStepsPerSecond = 60;
const millisecondsPerSecond = 1_000;
const boundaryThickness = 200;
const offscreenSideBoundaryExtension = 10_000;
const websiteGravityViewportHeightsPerSecondSquared = 1.9;
const websiteDropOverrides = {
  initialAngle: 0,
  initialAngularVelocity: 0,
} as const;

export const matchGameDropPhysics = {
  angularDamping: 0.012,
  angularVelocityBase: 1.2,
  angularVelocityImpactMultiplier: 0.2,
  boundaryFriction: 0.48,
  boundaryRestitution: 0.22,
  collisionBodyScale: 0.94,
  dropVelocityBase: 18,
  dropVelocityMaximum: 102,
  dropVelocityRankGrowth: 2.65,
  gravityMagnitude: 13.92,
  heavyStampRestitution: 0.14,
  horizontalVelocityBase: 18,
  horizontalVelocityImpactMultiplier: 4.5,
  impactRankGrowth: 0.055,
  lightStampRestitution: 0.34,
  linearDamping: 0.03,
  massBase: 0.82,
  massGrowth: 1.22,
  massMaximum: 16,
  massMultiplier: 3,
  maximumImpactScale: 2.25,
  maximumInitialRotation: Math.PI / 18,
  stampFriction: 0.52,
} as const;

export const pandaDropPresentation = {
  fixedStepMilliseconds: millisecondsPerSecond / 120,
  maximumFrameMilliseconds: millisecondsPerSecond / 30,
  reducedMotionSimulationLimitMilliseconds: 60 * millisecondsPerSecond,
  settlingTimeScale: 2.4,
  timeScale: 1,
} as const;

// Generated by the game's SummitStampContour.collisionPolygon(maximumVertexCount: 10)
// from assets/menimals/panda-wielka.png. SpriteKit uses a y-up coordinate system,
// so y is mirrored when the vertices enter the browser's y-down physics world.
export const giantPandaCollisionPolygon = [
  { x: 0.3862, y: 0.2573 },
  { x: 0.3042, y: 0.4263 },
  { x: 0.0073, y: 0.4429 },
  { x: -0.312, y: 0.4243 },
  { x: -0.3843, y: 0.2563 },
  { x: -0.3657, y: -0.2427 },
  { x: -0.2856, y: -0.4214 },
  { x: 0.1196, y: -0.4468 },
  { x: 0.3081, y: -0.4009 },
  { x: 0.3608, y: -0.2339 },
] as const;

export type PandaDropArena = {
  readonly height: number;
  readonly size: number;
  readonly width: number;
};

export type PandaDropPose = {
  readonly angle: number;
  readonly centerX: number;
  readonly isSettled: boolean;
  readonly topY: number;
  readonly x: number;
  readonly y: number;
};

export type PandaDropMotion = {
  readonly angularVelocity: number;
  readonly velocityX: number;
  readonly velocityY: number;
};

export type PandaDropTrajectoryFrame = {
  readonly atMilliseconds: number;
  readonly pose: PandaDropPose;
};

export type PandaDropTrajectory = {
  readonly durationMilliseconds: number;
  readonly finalPose: PandaDropPose;
  readonly frames: readonly PandaDropTrajectoryFrame[];
};

export type PandaDropRelease = {
  readonly motion: PandaDropMotion;
  readonly pose: PandaDropPose;
};

function tierRank(tierIndex: number) {
  return Math.min(Math.max(tierIndex, 0), maximumRegularTierIndex + 1);
}

export function dropVelocityForTier(tierIndex: number) {
  return Math.min(
    matchGameDropPhysics.dropVelocityBase +
      tierRank(tierIndex) * matchGameDropPhysics.dropVelocityRankGrowth,
    matchGameDropPhysics.dropVelocityMaximum,
  );
}

export function impactScaleForTier(tierIndex: number) {
  return Math.min(
    1 + tierRank(tierIndex) * matchGameDropPhysics.impactRankGrowth,
    matchGameDropPhysics.maximumImpactScale,
  );
}

export function massForTier(tierIndex: number) {
  const gameMass = Math.min(
    matchGameDropPhysics.massBase *
      matchGameDropPhysics.massGrowth ** tierRank(tierIndex),
    matchGameDropPhysics.massMaximum,
  );

  return gameMass * matchGameDropPhysics.massMultiplier;
}

export function restitutionForTier(tierIndex: number) {
  const weightProgress = Math.min(
    Math.max(tierRank(tierIndex) / (maximumRegularTierIndex + 1), 0),
    1,
  );

  return (
    matchGameDropPhysics.lightStampRestitution -
    (matchGameDropPhysics.lightStampRestitution -
      matchGameDropPhysics.heavyStampRestitution) *
      Math.sqrt(weightProgress)
  );
}

const giantPandaImpactScale = impactScaleForTier(giantPandaTierIndex);

export const giantPandaDropPhysics = {
  angularVelocityMagnitude:
    matchGameDropPhysics.angularVelocityBase +
    giantPandaImpactScale *
      matchGameDropPhysics.angularVelocityImpactMultiplier,
  downwardVelocity: dropVelocityForTier(giantPandaTierIndex),
  horizontalVelocityMagnitude:
    matchGameDropPhysics.horizontalVelocityBase +
    giantPandaImpactScale *
      matchGameDropPhysics.horizontalVelocityImpactMultiplier,
  mass: massForTier(giantPandaTierIndex),
  restitution: restitutionForTier(giantPandaTierIndex),
} as const;

function randomSignedMagnitude(magnitude: number, randomUnit: () => number) {
  return (randomUnit() * 2 - 1) * magnitude;
}

function pixelsPerSecondToMatter(velocity: number) {
  return velocity / matterBaseStepsPerSecond;
}

function radiansPerSecondToMatter(velocity: number) {
  return velocity / matterBaseStepsPerSecond;
}

function matterToRadiansPerSecond(velocity: number) {
  return velocity * matterBaseStepsPerSecond;
}

function matterToPixelsPerSecond(velocity: number) {
  return velocity * matterBaseStepsPerSecond;
}

function rotate(point: Matter.Vector, angle: number) {
  const cosine = Math.cos(angle);
  const sine = Math.sin(angle);

  return {
    x: point.x * cosine - point.y * sine,
    y: point.x * sine + point.y * cosine,
  };
}

function collisionVertices(size: number) {
  return giantPandaCollisionPolygon.map((point) => ({
    x: point.x * size * matchGameDropPhysics.collisionBodyScale,
    y: -point.y * size * matchGameDropPhysics.collisionBodyScale,
  }));
}

function createBoundary(
  x: number,
  y: number,
  width: number,
  height: number,
  restitution: number = matchGameDropPhysics.boundaryRestitution,
) {
  const boundary = Bodies.rectangle(x, y, width, height, { isStatic: true });
  Body.set(boundary, {
    friction: matchGameDropPhysics.boundaryFriction,
    frictionStatic: matchGameDropPhysics.boundaryFriction,
    restitution,
  });

  return boundary;
}

export class PandaDropSimulation {
  readonly arena: PandaDropArena;
  readonly body: MatterBody;
  readonly engine: MatterEngine;
  readonly collisionCenter: Matter.Vector;
  private boundaryContact = false;

  constructor(
    arena: PandaDropArena,
    randomUnit: () => number = Math.random,
    release?: PandaDropRelease,
  ) {
    this.arena = arena;
    this.engine = Engine.create({ enableSleeping: true });
    this.engine.gravity.x = 0;
    this.engine.gravity.y = 1;
    this.engine.gravity.scale =
      (arena.height * websiteGravityViewportHeightsPerSecondSquared) /
      millisecondsPerSecond ** 2;

    const vertices = collisionVertices(arena.size);
    this.collisionCenter = Vertices.centre(vertices);
    const angle = release?.pose.angle ?? websiteDropOverrides.initialAngle;
    const visualCenter = release
      ? {
          x: release.pose.x + arena.size / 2,
          y: release.pose.y + arena.size / 2,
        }
      : {
          x: arena.width / 2,
          y: -arena.size / 2,
        };
    const collisionCenter = rotate(this.collisionCenter, angle);

    this.body = Bodies.fromVertices(
      visualCenter.x + collisionCenter.x,
      visualCenter.y + collisionCenter.y,
      [vertices],
      {
        friction: matchGameDropPhysics.stampFriction,
        frictionAir: 0,
        frictionStatic: matchGameDropPhysics.stampFriction,
        restitution: giantPandaDropPhysics.restitution,
        sleepThreshold: matterBaseStepsPerSecond,
      },
    );
    Body.setMass(this.body, giantPandaDropPhysics.mass);
    Body.setAngle(this.body, angle);
    const velocity = release?.motion ?? {
      angularVelocity: websiteDropOverrides.initialAngularVelocity,
      velocityX: randomSignedMagnitude(
        giantPandaDropPhysics.horizontalVelocityMagnitude,
        randomUnit,
      ),
      velocityY: giantPandaDropPhysics.downwardVelocity,
    };
    Body.setVelocity(this.body, {
      x: pixelsPerSecondToMatter(velocity.velocityX),
      y: pixelsPerSecondToMatter(velocity.velocityY),
    });
    Body.setAngularVelocity(
      this.body,
      radiansPerSecondToMatter(velocity.angularVelocity),
    );

    const sideBoundaryHeight =
      arena.height + offscreenSideBoundaryExtension * 2;
    const boundaries = [
      createBoundary(
        arena.width / 2,
        arena.height + boundaryThickness / 2,
        arena.width + boundaryThickness * 2,
        boundaryThickness,
        matchGameDropPhysics.lightStampRestitution,
      ),
      createBoundary(
        -boundaryThickness / 2,
        arena.height / 2,
        boundaryThickness,
        sideBoundaryHeight,
      ),
      createBoundary(
        arena.width + boundaryThickness / 2,
        arena.height / 2,
        boundaryThickness,
        sideBoundaryHeight,
      ),
    ];

    Composite.add(this.engine.world, [this.body, ...boundaries]);
    Events.on(this.engine, "collisionStart", (event) => {
      this.boundaryContact ||= event.pairs.some(
        (pair) => pair.bodyA === this.body || pair.bodyB === this.body,
      );
    });
  }

  get hasBoundaryContact() {
    return this.boundaryContact;
  }

  get isSettled() {
    return this.body.isSleeping;
  }

  get motion(): PandaDropMotion {
    const velocity = Body.getVelocity(this.body);

    return {
      angularVelocity: matterToRadiansPerSecond(
        Body.getAngularVelocity(this.body),
      ),
      velocityX: matterToPixelsPerSecond(velocity.x),
      velocityY: matterToPixelsPerSecond(velocity.y),
    };
  }

  get pose(): PandaDropPose {
    const collisionCenter = rotate(this.collisionCenter, this.body.angle);
    const centerX = this.body.position.x - collisionCenter.x;
    const centerY = this.body.position.y - collisionCenter.y;

    return {
      angle: this.body.angle,
      centerX,
      isSettled: this.isSettled,
      topY: this.body.bounds.min.y,
      x: centerX - this.arena.size / 2,
      y: centerY - this.arena.size / 2,
    };
  }

  step(milliseconds: number) {
    if (this.isSettled) {
      return;
    }

    const seconds = milliseconds / millisecondsPerSecond;
    const velocity = Body.getVelocity(this.body);
    const linearDecay = Math.exp(
      -matchGameDropPhysics.linearDamping * seconds,
    );
    const angularDecay = Math.exp(
      -matchGameDropPhysics.angularDamping * seconds,
    );

    Body.setVelocity(this.body, {
      x: velocity.x * linearDecay,
      y: velocity.y * linearDecay,
    });
    Body.setAngularVelocity(
      this.body,
      Body.getAngularVelocity(this.body) * angularDecay,
    );
    Engine.update(this.engine, milliseconds);
  }
}

function interpolate(start: number, end: number, progress: number) {
  return start + (end - start) * progress;
}

function interpolatePose(
  start: PandaDropPose,
  end: PandaDropPose,
  progress: number,
): PandaDropPose {
  return {
    angle: interpolate(start.angle, end.angle, progress),
    centerX: interpolate(start.centerX, end.centerX, progress),
    isSettled: end.isSettled && progress === 1,
    topY: interpolate(start.topY, end.topY, progress),
    x: interpolate(start.x, end.x, progress),
    y: interpolate(start.y, end.y, progress),
  };
}

export function createPandaDropTrajectory(
  arena: PandaDropArena,
  randomUnit: () => number = Math.random,
  release?: PandaDropRelease,
): PandaDropTrajectory {
  const simulation = new PandaDropSimulation(arena, randomUnit, release);
  const frames: PandaDropTrajectoryFrame[] = [
    { atMilliseconds: 0, pose: simulation.pose },
  ];
  let durationMilliseconds = 0;
  let simulatedMilliseconds = 0;

  while (
    !simulation.isSettled &&
    simulatedMilliseconds <
      pandaDropPresentation.reducedMotionSimulationLimitMilliseconds
  ) {
    simulation.step(pandaDropPresentation.fixedStepMilliseconds);
    simulatedMilliseconds += pandaDropPresentation.fixedStepMilliseconds;
    const timeScale = simulation.hasBoundaryContact
      ? pandaDropPresentation.settlingTimeScale
      : pandaDropPresentation.timeScale;
    durationMilliseconds +=
      pandaDropPresentation.fixedStepMilliseconds / timeScale;
    frames.push({ atMilliseconds: durationMilliseconds, pose: simulation.pose });
  }

  return {
    durationMilliseconds,
    finalPose: frames.at(-1)?.pose ?? simulation.pose,
    frames,
  };
}

export function samplePandaDropTrajectory(
  trajectory: PandaDropTrajectory,
  atMilliseconds: number,
): PandaDropPose {
  const clampedMilliseconds = Math.min(
    Math.max(atMilliseconds, 0),
    trajectory.durationMilliseconds,
  );
  let low = 0;
  let high = trajectory.frames.length - 1;

  while (low < high) {
    const middle = Math.floor((low + high) / 2);
    if (trajectory.frames[middle].atMilliseconds < clampedMilliseconds) {
      low = middle + 1;
    } else {
      high = middle;
    }
  }

  const end = trajectory.frames[low];
  const start = trajectory.frames[Math.max(low - 1, 0)];
  const frameDuration = end.atMilliseconds - start.atMilliseconds;
  const progress =
    frameDuration === 0
      ? 1
      : (clampedMilliseconds - start.atMilliseconds) / frameDuration;

  return interpolatePose(start.pose, end.pose, progress);
}
