import Matter, { type Body as MatterBody, type Engine as MatterEngine } from "matter-js";

const { Bodies, Body, Composite, Engine, Events, Vertices } = Matter;

const kiwiTierIndex = 0;
const giantPandaTierIndex = 9;
const maximumRegularTierIndex = 12;
const matterBaseStepsPerSecond = 60;
const millisecondsPerSecond = 1_000;
const boundaryThickness = 200;
const offscreenSideBoundaryExtension = 10_000;
const websiteGravityViewportHeightsPerSecondSquared = 1.9;
const websiteDropOverrides = {
  initialAngle: 0,
  initialAngularVelocity: 0,
} as const;

export const matchGameDropPhysics = {
  angularDamping: 0.012,
  angularVelocityBase: 1.2,
  angularVelocityImpactMultiplier: 0.2,
  boundaryFriction: 0.48,
  boundaryRestitution: 0.22,
  collisionBodyScale: 0.94,
  dropVelocityBase: 18,
  dropVelocityMaximum: 102,
  dropVelocityRankGrowth: 2.65,
  gravityMagnitude: 13.92,
  heavyStampRestitution: 0.14,
  horizontalVelocityBase: 18,
  horizontalVelocityImpactMultiplier: 4.5,
  impactRankGrowth: 0.055,
  lightStampRestitution: 0.34,
  linearDamping: 0.03,
  massBase: 0.82,
  massGrowth: 1.22,
  massMaximum: 16,
  massMultiplier: 3,
  maximumImpactScale: 2.25,
  maximumInitialRotation: Math.PI / 18,
  stampFriction: 0.52,
} as const;

export const pandaDropPresentation = {
  fixedStepMilliseconds: millisecondsPerSecond / 120,
  maximumFrameMilliseconds: millisecondsPerSecond / 30,
  reducedMotionSimulationLimitMilliseconds: 60 * millisecondsPerSecond,
  settlingTimeScale: 2.4,
  timeScale: 1,
} as const;

// Generated by the game's SummitStampContour.collisionPolygon(maximumVertexCount: 10)
// from assets/menimals/panda-wielka.png. SpriteKit uses a y-up coordinate system,
// so y is mirrored when the vertices enter the browser's y-down physics world.
export const giantPandaCollisionPolygon = [
  { x: 0.3862, y: 0.2573 },
  { x: 0.3042, y: 0.4263 },
  { x: 0.0073, y: 0.4429 },
  { x: -0.312, y: 0.4243 },
  { x: -0.3843, y: 0.2563 },
  { x: -0.3657, y: -0.2427 },
  { x: -0.2856, y: -0.4214 },
  { x: 0.1196, y: -0.4468 },
  { x: 0.3081, y: -0.4009 },
  { x: 0.3608, y: -0.2339 },
] as const;

// Generated by the same SummitStampContour.collisionPolygon(maximumVertexCount: 10)
// path as the panda, from assets/menimals/kiwi.png.
export const kiwiCollisionPolygon = [
  { x: 0.3276, y: 0.2183 },
  { x: 0.1479, y: 0.4136 },
  { x: -0.1274, y: 0.4302 },
  { x: -0.1528, y: 0.4214 },
  { x: -0.3491, y: 0.2095 },
  { x: -0.4341, y: -0.2183 },
  { x: -0.3452, y: -0.396 },
  { x: 0.1187, y: -0.4458 },
  { x: 0.3071, y: -0.4019 },
  { x: 0.4272, y: -0.2622 },
] as const;

export const menimalDropConfig = {
  panda: {
    collisionPolygon: giantPandaCollisionPolygon,
    initialCenterXRatio: 0.62,
    initialTopOffsetRatio: 0,
    sizeRatio: 1,
    tierIndex: giantPandaTierIndex,
  },
  kiwi: {
    collisionPolygon: kiwiCollisionPolygon,
    initialCenterXRatio: 0.38,
    initialTopOffsetRatio: -0.55,
    sizeRatio: 0.75,
    tierIndex: kiwiTierIndex,
  },
} as const;

export type MenimalKind = keyof typeof menimalDropConfig;

export const menimalKinds = Object.keys(menimalDropConfig) as MenimalKind[];

export type PandaDropArena = {
  readonly height: number;
  readonly size: number;
  readonly width: number;
};

export type PandaDropPose = {
  readonly angle: number;
  readonly centerX: number;
  readonly isSettled: boolean;
  readonly topY: number;
  readonly x: number;
  readonly y: number;
};

export type PandaDropMotion = {
  readonly angularVelocity: number;
  readonly velocityX: number;
  readonly velocityY: number;
};

export type PandaDropTrajectoryFrame = {
  readonly atMilliseconds: number;
  readonly pose: PandaDropPose;
};

export type PandaDropTrajectory = {
  readonly durationMilliseconds: number;
  readonly finalPose: PandaDropPose;
  readonly frames: readonly PandaDropTrajectoryFrame[];
};

export type PandaDropRelease = {
  readonly motion: PandaDropMotion;
  readonly pose: PandaDropPose;
};

export type MenimalDropReleases = Record<MenimalKind, PandaDropRelease>;

export type MenimalDropPoses = Record<MenimalKind, PandaDropPose>;

export type MenimalDropTrajectoryFrame = {
  readonly atMilliseconds: number;
  readonly poses: MenimalDropPoses;
};

export type MenimalDropTrajectory = {
  readonly durationMilliseconds: number;
  readonly finalPoses: MenimalDropPoses;
  readonly frames: readonly MenimalDropTrajectoryFrame[];
};

export type PandaDropWorldOptions = {
  readonly kiwiRelease?: PandaDropRelease;
};

type MenimalBodyState = {
  readonly body: MatterBody;
  readonly collisionCenter: Matter.Vector;
  readonly kind: MenimalKind;
  readonly size: number;
};

function tierRank(tierIndex: number) {
  return Math.min(Math.max(tierIndex, 0), maximumRegularTierIndex + 1);
}

export function dropVelocityForTier(tierIndex: number) {
  return Math.min(
    matchGameDropPhysics.dropVelocityBase +
      tierRank(tierIndex) * matchGameDropPhysics.dropVelocityRankGrowth,
    matchGameDropPhysics.dropVelocityMaximum,
  );
}

export function impactScaleForTier(tierIndex: number) {
  return Math.min(
    1 + tierRank(tierIndex) * matchGameDropPhysics.impactRankGrowth,
    matchGameDropPhysics.maximumImpactScale,
  );
}

export function massForTier(tierIndex: number) {
  const gameMass = Math.min(
    matchGameDropPhysics.massBase *
      matchGameDropPhysics.massGrowth ** tierRank(tierIndex),
    matchGameDropPhysics.massMaximum,
  );

  return gameMass * matchGameDropPhysics.massMultiplier;
}

export function restitutionForTier(tierIndex: number) {
  const weightProgress = Math.min(
    Math.max(tierRank(tierIndex) / (maximumRegularTierIndex + 1), 0),
    1,
  );

  return (
    matchGameDropPhysics.lightStampRestitution -
    (matchGameDropPhysics.lightStampRestitution -
      matchGameDropPhysics.heavyStampRestitution) *
      Math.sqrt(weightProgress)
  );
}

function dropPhysicsForTier(tierIndex: number) {
  const impactScale = impactScaleForTier(tierIndex);

  return {
    angularVelocityMagnitude:
      matchGameDropPhysics.angularVelocityBase +
      impactScale * matchGameDropPhysics.angularVelocityImpactMultiplier,
    downwardVelocity: dropVelocityForTier(tierIndex),
    horizontalVelocityMagnitude:
      matchGameDropPhysics.horizontalVelocityBase +
      impactScale * matchGameDropPhysics.horizontalVelocityImpactMultiplier,
    mass: massForTier(tierIndex),
    restitution: restitutionForTier(tierIndex),
  };
}

export const giantPandaDropPhysics = dropPhysicsForTier(giantPandaTierIndex);

export const kiwiDropPhysics = {
  ...dropPhysicsForTier(kiwiTierIndex),
  sizeRatio: menimalDropConfig.kiwi.sizeRatio,
};

function randomSignedMagnitude(magnitude: number, randomUnit: () => number) {
  return (randomUnit() * 2 - 1) * magnitude;
}

function pixelsPerSecondToMatter(velocity: number) {
  return velocity / matterBaseStepsPerSecond;
}

function radiansPerSecondToMatter(velocity: number) {
  return velocity / matterBaseStepsPerSecond;
}

function matterToRadiansPerSecond(velocity: number) {
  return velocity * matterBaseStepsPerSecond;
}

function matterToPixelsPerSecond(velocity: number) {
  return velocity * matterBaseStepsPerSecond;
}

function rotate(point: Matter.Vector, angle: number) {
  const cosine = Math.cos(angle);
  const sine = Math.sin(angle);

  return {
    x: point.x * cosine - point.y * sine,
    y: point.x * sine + point.y * cosine,
  };
}

function collisionVertices(size: number, polygon: readonly Matter.Vector[]) {
  return polygon.map((point) => ({
    x: point.x * size * matchGameDropPhysics.collisionBodyScale,
    y: -point.y * size * matchGameDropPhysics.collisionBodyScale,
  }));
}

function createBoundary(
  x: number,
  y: number,
  width: number,
  height: number,
  restitution: number = matchGameDropPhysics.boundaryRestitution,
) {
  const boundary = Bodies.rectangle(x, y, width, height, { isStatic: true });
  Body.set(boundary, {
    friction: matchGameDropPhysics.boundaryFriction,
    frictionStatic: matchGameDropPhysics.boundaryFriction,
    restitution,
  });

  return boundary;
}

type CreateMenimalBodyParams = {
  arena: PandaDropArena;
  initialCenterX: number;
  kind: MenimalKind;
  randomUnit: () => number;
  release?: PandaDropRelease;
};

function createMenimalBodyState(p: CreateMenimalBodyParams): MenimalBodyState {
  const config = menimalDropConfig[p.kind];
  const physics = dropPhysicsForTier(config.tierIndex);
  const size = p.arena.size * config.sizeRatio;
  const vertices = collisionVertices(size, config.collisionPolygon);
  const collisionCenter = Vertices.centre(vertices);
  const angle = p.release?.pose.angle ?? websiteDropOverrides.initialAngle;
  const visualCenter = p.release
    ? {
        x: p.release.pose.x + size / 2,
        y: p.release.pose.y + size / 2,
      }
    : {
        x: p.initialCenterX,
        y:
          -size / 2 +
          p.arena.size * config.initialTopOffsetRatio,
      };
  const rotatedCollisionCenter = rotate(collisionCenter, angle);
  const body = Bodies.fromVertices(
    visualCenter.x + rotatedCollisionCenter.x,
    visualCenter.y + rotatedCollisionCenter.y,
    [vertices],
    {
      friction: matchGameDropPhysics.stampFriction,
      frictionAir: 0,
      frictionStatic: matchGameDropPhysics.stampFriction,
      restitution: physics.restitution,
      sleepThreshold: matterBaseStepsPerSecond,
    },
  );
  const motion = p.release?.motion ?? {
    angularVelocity: websiteDropOverrides.initialAngularVelocity,
    velocityX: randomSignedMagnitude(
      physics.horizontalVelocityMagnitude,
      p.randomUnit,
    ),
    velocityY: physics.downwardVelocity,
  };

  Body.setMass(body, physics.mass);
  Body.setAngle(body, angle);
  Body.setVelocity(body, {
    x: pixelsPerSecondToMatter(motion.velocityX),
    y: pixelsPerSecondToMatter(motion.velocityY),
  });
  Body.setAngularVelocity(
    body,
    radiansPerSecondToMatter(motion.angularVelocity),
  );

  return { body, collisionCenter, kind: p.kind, size };
}

function bodyExtents(body: MatterBody) {
  let bottom = Number.NEGATIVE_INFINITY;
  let left = Number.POSITIVE_INFINITY;
  let right = Number.NEGATIVE_INFINITY;
  let top = Number.POSITIVE_INFINITY;

  for (const vertex of body.vertices) {
    bottom = Math.max(bottom, vertex.y);
    left = Math.min(left, vertex.x);
    right = Math.max(right, vertex.x);
    top = Math.min(top, vertex.y);
  }

  return { bottom, left, right, top };
}

function motionForBody(body: MatterBody): PandaDropMotion {
  const velocity = Body.getVelocity(body);

  return {
    angularVelocity: matterToRadiansPerSecond(Body.getAngularVelocity(body)),
    velocityX: matterToPixelsPerSecond(velocity.x),
    velocityY: matterToPixelsPerSecond(velocity.y),
  };
}

export class PandaDropSimulation {
  readonly arena: PandaDropArena;
  readonly body: MatterBody;
  readonly engine: MatterEngine;
  readonly collisionCenter: Matter.Vector;
  readonly kiwiBody: MatterBody | null;
  private boundaryContact = false;
  private readonly ceiling: MatterBody;
  private ceilingIsActive = false;
  private menimalContact = false;
  private readonly pandaState: MenimalBodyState;
  private readonly kiwiState: MenimalBodyState | null;
  private readonly states: readonly MenimalBodyState[];

  constructor(
    arena: PandaDropArena,
    randomUnit: () => number = Math.random,
    release?: PandaDropRelease,
    options?: PandaDropWorldOptions,
  ) {
    this.arena = arena;
    this.engine = Engine.create({ enableSleeping: true });
    this.engine.gravity.x = 0;
    this.engine.gravity.y = 1;
    this.engine.gravity.scale =
      (arena.height * websiteGravityViewportHeightsPerSecondSquared) /
      millisecondsPerSecond ** 2;

    this.pandaState = createMenimalBodyState({
      arena,
      initialCenterX: options
        ? arena.width * menimalDropConfig.panda.initialCenterXRatio
        : arena.width / 2,
      kind: "panda",
      randomUnit,
      release,
    });
    this.kiwiState = options
      ? createMenimalBodyState({
          arena,
          initialCenterX:
            arena.width * menimalDropConfig.kiwi.initialCenterXRatio,
          kind: "kiwi",
          randomUnit,
          release: options.kiwiRelease,
        })
      : null;
    this.states = this.kiwiState
      ? [this.pandaState, this.kiwiState]
      : [this.pandaState];
    this.body = this.pandaState.body;
    this.collisionCenter = this.pandaState.collisionCenter;
    this.kiwiBody = this.kiwiState?.body ?? null;

    const sideBoundaryHeight =
      arena.height + offscreenSideBoundaryExtension * 2;
    this.ceiling = createBoundary(
      arena.width / 2,
      -boundaryThickness / 2,
      arena.width + boundaryThickness * 2,
      boundaryThickness,
    );
    const boundaries = [
      createBoundary(
        arena.width / 2,
        arena.height + boundaryThickness / 2,
        arena.width + boundaryThickness * 2,
        boundaryThickness,
        matchGameDropPhysics.lightStampRestitution,
      ),
      createBoundary(
        -boundaryThickness / 2,
        arena.height / 2,
        boundaryThickness,
        sideBoundaryHeight,
      ),
      createBoundary(
        arena.width + boundaryThickness / 2,
        arena.height / 2,
        boundaryThickness,
        sideBoundaryHeight,
      ),
    ];

    Composite.add(this.engine.world, [
      ...this.states.map((state) => state.body),
      ...boundaries,
    ]);
    this.activateCeilingWhenMenimalsAreInside();
    const dynamicBodies = new Set(this.states.map((state) => state.body));
    Events.on(this.engine, "collisionStart", (event) => {
      for (const pair of event.pairs) {
        const bodyAIsDynamic = dynamicBodies.has(pair.bodyA);
        const bodyBIsDynamic = dynamicBodies.has(pair.bodyB);
        this.boundaryContact ||=
          bodyAIsDynamic !== bodyBIsDynamic &&
          (pair.bodyA.isStatic || pair.bodyB.isStatic);
        this.menimalContact ||= bodyAIsDynamic && bodyBIsDynamic;
      }
    });
  }

  get hasBoundaryContact() {
    return this.boundaryContact;
  }

  get hasMenimalContact() {
    return this.menimalContact;
  }

  get isSettled() {
    return this.states.every((state) => state.body.isSleeping);
  }

  get motion() {
    return motionForBody(this.body);
  }

  get kiwiMotion() {
    return motionForBody(this.requiredKiwiState.body);
  }

  get pose() {
    return this.poseFor(this.pandaState);
  }

  get kiwiPose() {
    return this.poseFor(this.requiredKiwiState);
  }

  private get requiredKiwiState() {
    if (!this.kiwiState) {
      throw new Error("Kiwi is not active in this simulation");
    }

    return this.kiwiState;
  }

  private poseFor(state: MenimalBodyState): PandaDropPose {
    const collisionCenter = rotate(state.collisionCenter, state.body.angle);
    const centerX = state.body.position.x - collisionCenter.x;
    const centerY = state.body.position.y - collisionCenter.y;

    return {
      angle: state.body.angle,
      centerX,
      isSettled: state.body.isSleeping,
      topY: bodyExtents(state.body).top,
      x: centerX - state.size / 2,
      y: centerY - state.size / 2,
    };
  }
  private activateCeilingWhenMenimalsAreInside() {
    if (
      this.ceilingIsActive ||
      this.states.some((state) => bodyExtents(state.body).top < 0)
    ) {
      return;
    }

    Composite.add(this.engine.world, this.ceiling);
    this.ceilingIsActive = true;
  }

  private keepMenimalsBelowActiveCeiling() {
    if (!this.ceilingIsActive) {
      return;
    }

    for (const state of this.states) {
      const top = bodyExtents(state.body).top;
      if (top < 0) {
        Body.translate(state.body, { x: 0, y: -top });
      }
    }
  }

  step(milliseconds: number) {
    if (this.isSettled) {
      return;
    }

    const seconds = milliseconds / millisecondsPerSecond;
    const linearDecay = Math.exp(
      -matchGameDropPhysics.linearDamping * seconds,
    );
    const angularDecay = Math.exp(
      -matchGameDropPhysics.angularDamping * seconds,
    );

    for (const state of this.states) {
      const velocity = Body.getVelocity(state.body);
      Body.setVelocity(state.body, {
        x: velocity.x * linearDecay,
        y: velocity.y * linearDecay,
      });
      Body.setAngularVelocity(
        state.body,
        Body.getAngularVelocity(state.body) * angularDecay,
      );
    }
    Engine.update(this.engine, milliseconds);
    this.keepMenimalsBelowActiveCeiling();
    this.activateCeilingWhenMenimalsAreInside();
  }
}

function interpolate(start: number, end: number, progress: number) {
  return start + (end - start) * progress;
}

function interpolatePose(
  start: PandaDropPose,
  end: PandaDropPose,
  progress: number,
): PandaDropPose {
  return {
    angle: interpolate(start.angle, end.angle, progress),
    centerX: interpolate(start.centerX, end.centerX, progress),
    isSettled: end.isSettled && progress === 1,
    topY: interpolate(start.topY, end.topY, progress),
    x: interpolate(start.x, end.x, progress),
    y: interpolate(start.y, end.y, progress),
  };
}

export function createPandaDropTrajectory(
  arena: PandaDropArena,
  randomUnit: () => number = Math.random,
  release?: PandaDropRelease,
): PandaDropTrajectory {
  const simulation = new PandaDropSimulation(arena, randomUnit, release);
  const frames: PandaDropTrajectoryFrame[] = [
    { atMilliseconds: 0, pose: simulation.pose },
  ];
  let durationMilliseconds = 0;
  let simulatedMilliseconds = 0;

  while (
    !simulation.isSettled &&
    simulatedMilliseconds <
      pandaDropPresentation.reducedMotionSimulationLimitMilliseconds
  ) {
    simulation.step(pandaDropPresentation.fixedStepMilliseconds);
    simulatedMilliseconds += pandaDropPresentation.fixedStepMilliseconds;
    const timeScale = simulation.hasBoundaryContact
      ? pandaDropPresentation.settlingTimeScale
      : pandaDropPresentation.timeScale;
    durationMilliseconds +=
      pandaDropPresentation.fixedStepMilliseconds / timeScale;
    frames.push({ atMilliseconds: durationMilliseconds, pose: simulation.pose });
  }

  return {
    durationMilliseconds,
    finalPose: frames.at(-1)?.pose ?? simulation.pose,
    frames,
  };
}

function menimalPoses(simulation: PandaDropSimulation): MenimalDropPoses {
  return {
    kiwi: simulation.kiwiPose,
    panda: simulation.pose,
  };
}

export function createMenimalDropTrajectory(
  arena: PandaDropArena,
  randomUnit: () => number = Math.random,
  releases?: MenimalDropReleases,
): MenimalDropTrajectory {
  const simulation = new PandaDropSimulation(
    arena,
    randomUnit,
    releases?.panda,
    { kiwiRelease: releases?.kiwi },
  );
  const frames: MenimalDropTrajectoryFrame[] = [
    { atMilliseconds: 0, poses: menimalPoses(simulation) },
  ];
  let durationMilliseconds = 0;
  let simulatedMilliseconds = 0;

  while (
    !simulation.isSettled &&
    simulatedMilliseconds <
      pandaDropPresentation.reducedMotionSimulationLimitMilliseconds
  ) {
    simulation.step(pandaDropPresentation.fixedStepMilliseconds);
    simulatedMilliseconds += pandaDropPresentation.fixedStepMilliseconds;
    const timeScale = simulation.hasBoundaryContact
      ? pandaDropPresentation.settlingTimeScale
      : pandaDropPresentation.timeScale;
    durationMilliseconds +=
      pandaDropPresentation.fixedStepMilliseconds / timeScale;
    frames.push({
      atMilliseconds: durationMilliseconds,
      poses: menimalPoses(simulation),
    });
  }

  return {
    durationMilliseconds,
    finalPoses: frames.at(-1)?.poses ?? menimalPoses(simulation),
    frames,
  };
}

function sampledFrames<TFrame extends { readonly atMilliseconds: number }>(
  frames: readonly TFrame[],
  durationMilliseconds: number,
  atMilliseconds: number,
) {
  const clampedMilliseconds = Math.min(
    Math.max(atMilliseconds, 0),
    durationMilliseconds,
  );
  let low = 0;
  let high = frames.length - 1;

  while (low < high) {
    const middle = Math.floor((low + high) / 2);
    if (frames[middle].atMilliseconds < clampedMilliseconds) {
      low = middle + 1;
    } else {
      high = middle;
    }
  }

  const end = frames[low];
  const start = frames[Math.max(low - 1, 0)];
  const frameDuration = end.atMilliseconds - start.atMilliseconds;
  const progress =
    frameDuration === 0
      ? 1
      : (clampedMilliseconds - start.atMilliseconds) / frameDuration;

  return { end, progress, start };
}

export function samplePandaDropTrajectory(
  trajectory: PandaDropTrajectory,
  atMilliseconds: number,
): PandaDropPose {
  const sample = sampledFrames(
    trajectory.frames,
    trajectory.durationMilliseconds,
    atMilliseconds,
  );

  return interpolatePose(sample.start.pose, sample.end.pose, sample.progress);
}

export function sampleMenimalDropTrajectory(
  trajectory: MenimalDropTrajectory,
  atMilliseconds: number,
): MenimalDropPoses {
  const sample = sampledFrames(
    trajectory.frames,
    trajectory.durationMilliseconds,
    atMilliseconds,
  );

  return {
    kiwi: interpolatePose(
      sample.start.poses.kiwi,
      sample.end.poses.kiwi,
      sample.progress,
    ),
    panda: interpolatePose(
      sample.start.poses.panda,
      sample.end.poses.panda,
      sample.progress,
    ),
  };
}
